### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')     at editSpamButton (<anonymous>:78:13)

### ISSUE THREAD

**Issue by apambalik1337** [rahmatsubandi/Spam-chat-Whatsapp#1]
gak berhasil :(

**Comment by rahmatsubandi** [comment]
Gak berhasil nya dimana mas? Bisa info?

**Comment by apambalik1337** [comment]
> Gak berhasil nya dimana mas? Bisa info?

nih bang, bila gw ketik "bom" ngak jadi apa-apa
popup jugak tidak muncul

**Comment by rahmatsubandi** [comment]
> > Gak berhasil nya dimana mas? Bisa info?
> 
> nih bang, bila gw ketik "bom" ngak jadi apa-apa popup jugak tidak muncul

oke nanti saya cek bug nya ya

**Comment by rahmatsubandi** [comment]
Silahkan coba lagi ya
