### ISSUE TITLE
Di coba

### ISSUE THREAD

**Issue by yoseftea** [rahmatsubandi/Spam-chat-Whatsapp#2]

**Comment by rahmatsubandi** [comment]
Goodluck👍

**Comment by yoseftea** [comment]
Tidak bisa

Pada tanggal Kam, 6 Okt 2022 19.52, Rahmat Subandi ***@***.***>
menulis:

**Comment by rahmatsubandi** [comment]
> Tidak bisa Pada tanggal Kam, 6 Okt 2022 19.52, Rahmat Subandi ***@***.***> menulis:
> […](#)

Lampirkan ss nya, biar saya cek.

**Comment by yoseftea** [comment]
tidakn ada script nya
